# SPDX-FileCopyrightText: 2024-present Dan Pascu <dan@aethereal.link>
#
# SPDX-License-Identifier: AGPL-3.0-or-later


from collections.abc import Iterable
from typing import Protocol

__all__ = 'ComparableNumber', 'SupportsKeysAndGetItem'


class ComparableNumber[T: ComparableNumber](Protocol):  # noqa: PLW1641
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: T, /) -> bool: ...
    def __gt__(self, other: T, /) -> bool: ...
    def __le__(self, other: T, /) -> bool: ...
    def __ge__(self, other: T, /) -> bool: ...
    def __int__(self) -> int: ...


class SupportsKeysAndGetItem[K, V](Protocol):
    def keys(self) -> Iterable[K]: ...
    def __getitem__(self, key: K, /) -> V: ...
